run_config:
  stages: ["train", "evaluate"]
  seed: 42
  study_name: norman
  train_log_path: logs/random_forest/train/norman.log
  eval_log_path: logs/random_forest/evaluate/norman.log
  save_checkpoint_path: model/random_forest/norman/model.joblib
  load_checkpoint_path:
  save_best_only: true

device_config:
  device: "cpu"
  ddp_enabled: false
  use_mixed_precision: false

data_config:
  h5ad_path: data/norman/perturb_processed.h5ad
  condition_key: condition
  control_key: control
  condition_split_path: data/norman/norman_gene_heldout_split.yaml
  condition_split:
    train: []
    validation: []
    test: []

model_config:
  model: random_forest
  n_estimators: 300
  max_depth:
  n_jobs: -1

training_config: {}

evaluation_config:
  top_k_values: [1, 5, 10, 20, 40]
